---
name: RPM build in Fedora Copr
on:
  # Build only on pushes into master branch.
  push:
    branches: [master]

jobs:
  build:
    name: Submit a build from Fedora container
    # Run in Fedora container on Ubuntu VM (no direct Fedora support)
    container: fedora:latest
    runs-on: fedora-latest #ubuntu-latest

    steps:
      - name: Check out proper version of sources
        uses: actions/checkout@v1

      - name: Install API token for copr-cli
        env:
          API_TOKEN_CONTENT: ${{ secrets.COPR_API_TOKEN }}
        run: |
          mkdir -p "$HOME/.config"
          echo "$API_TOKEN_CONTENT" > "$HOME/.config/copr"

      - name: Install tooling for source RPM build
        run: |
          dnf -y install @development-tools @rpm-development-tools
          dnf -y install copr-cli make

      - name: Build the source RPM
        run: cd rpm && make srpm

      - name: Submit the build by uploading the source RPM
        run: copr-cli build signla-desktop  rpm/*.src.rpm
